capstone/intro/urls.py
from django.urls import path
from . import views

app_name = 'intro'
urlpatterns = [
    path('', views.main, name = 'main')
]

capstone/qna/urls.py
from django.urls import path
from . import views

app_name = 'qna'
urlpatterns = [
    path('', views.main, name = 'main'),
    path('write/', views.write, name = 'write'),
    path('current_page=<int:page>/', views.pageview, name = 'pageview'),
    path('<int:board_id>/', views.detail, name = 'detail'),
    path('<int:board_id>/delete', views.delete, name = 'delete'),
    path('search/', views.search, name='search'),
]

capstone/trend/urls.py
from django.urls import path
from . import views

app_name = 'trend'
urlpatterns = [
    path('', views.main, name = 'main')
]

capstone/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('', views.main, name='main'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.sucess, name='index'),
    path('search/', views.SearchFormView.as_view(), name='search'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("capstone.users.urls", namespace="users")),
    path("", include("capstone.search.urls", namespace="search")),
    path("intro/", include("capstone.intro.urls", namespace="intro")),
    path("qna/", include("capstone.qna.urls", namespace="qna")),
    path("trend/", include("capstone.trend.urls", namespace="trend")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

capstone/intro/models.py
from django.db import models

# Create your models here.

capstone/qna/models.py
from django.db import models

# Create your models here.

class TimeStamedModel(models.Model):
    create_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    
    
    class Meta:
        abstract = True


class Board(TimeStamedModel):
    title = models.CharField(max_length = 50) # 글 제목
    author = models.CharField(max_length = 15) # 작성자
    content = models.CharField(max_length = 500) # 내용
    image = models.ImageField(blank = True) # 이미지(사진)
    hits = models.IntegerField(default = 0) # 조회수
    password = models.CharField(max_length = 20)

    def __str__(self):
        return self.title

    

capstone/search/models.py
from django.db import models

# Create your models here.

capstone/trend/models.py
from django.db import models

# Create your models here.

capstone/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('C', "Custom"),
    ]

    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    user_name = models.CharField(blank=True, max_length=255)
    website = models.URLField(blank=True)
    bio = models.TextField(blank=True)
    email = models.CharField(blank=True, max_length=255)
    phone_number = models.CharField(blank=True, max_length=255)
    gender = models.CharField(blank=True, choices = GENDER_CHOICES, max_length=255)
    followers = models.ManyToManyField("self")
    following = models.ManyToManyField("self")



    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

capstone/qna/forms.py
from django import forms
from qna.models import Board

class WriteForm(forms.ModelForm):
    #password = forms.CharField(max_length = 50, label='', widget = forms.PasswordInput(attrs={'placeholder':'비밀번호'}))

    class Meta:
        model = Board

        fields = ['title', 'author', 'content', 'image', 'password']
        labels = {
            'title': "",
            'author': '',
            'content': '',
            'image': '이미지첨부',
            'password': '',
        }

        widgets = {
            'title': forms.TextInput(attrs={'placeholder':'제목'}),
            'author': forms.TextInput(attrs={'placeholder':'이름'}),
            'content': forms.TextInput(attrs={'placeholder':'내용 최대xx자'}),
            'password': forms.PasswordInput(attrs={'placeholder':'비밀번호'}),
        }          

capstone/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django import forms as django_forms

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

class SignUpForm(django_forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'name', 'username', 'password']
        labels = {
            'email': "",
            'name': '',
            'username': '',
            'password': '',
        }
        widgets = {
            'email': django_forms.TextInput(attrs={'placeholder':'이메일 주소'}),
            'name': django_forms.TextInput(attrs={'placeholder':'성명'}),
            'username': django_forms.TextInput(attrs={'placeholder':'사용자 이름'}),
            'password': django_forms.PasswordInput(attrs={'placeholder':'비밀번호'}),
        }           
        
    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

class LogInForm(django_forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']
        labels = {'username': '', 'password': '',}
        widgets = {
            'username': django_forms.TextInput(attrs={'placeholder':'사용자 이름'}),
            'password': django_forms.PasswordInput(attrs={'placeholder':'비밀번호'}),
        }     

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

class UserSearchForm(django_forms.Form):
    search_word = django_forms.CharField(label='Search Word')

capstone/intro/views.py
from django.shortcuts import render
from django.http import HttpResponse

def main(request):
    return HttpResponse("인트로")

capstone/qna/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from qna.models import Board
from qna.forms import WriteForm
from django.views import generic
from django.db.models import Q


rowsPerPage = 5 # 한 페이지에 보여줄 게시물 수
def main(request):
    return HttpResponseRedirect(reverse('qna:pageview', args=(1,))) # pageview로 인수(page)에 1을 넣어 넘겨줌

def pageview(request, page): 
    current_page = page # 페이지 번호
    # 화면에 띄울 게시물 (한 페이지에 보여줄 게시물 수) 
    boardList = Board.objects.order_by('-id')[rowsPerPage * (current_page-1):rowsPerPage * current_page]
    totalCnt = Board.objects.all().count() # 총 게시물수

    pagingHelperlns = pagingHelper() # 클래스 선언
    totalPageList = pagingHelperlns.getTotalPageList(totalCnt, rowsPerPage) # 총 게시물수와 한페이지당 보여줄 게시물수에 따라 페이지수를 결정함
    print ('totalPageList', totalPageList)
    return render(request, 'qna/main.html', {'boardList': boardList, 'totalCnt': totalCnt, 
                                            'current_page': current_page, 'totalPageList': totalPageList})

class pagingHelper:
    def getTotalPageList(self, total_cnt, rowsPerPage):
        if ((total_cnt % rowsPerPage) == 0):
            self.total_pages = int(total_cnt / rowsPerPage)
            print ('getTotalPage #1')
        else:
            self.total_pages = int((total_cnt / rowsPerPage) + 1)
            print ('getTotalPage #2')
        
        self.totalPageList = []
        for j in range(self.total_pages):
            self.totalPageList.append(j + 1)

        return self.totalPageList
    
    def __init__(self):
        self.total_pages = 0
        self.totalPageList = 0


def write(request): # 글 쓰기
    if request.method == 'GET':
        form = WriteForm()

        return render(request, 'qna/write.html', {'form': form})
    if request.method == 'POST':
        title = request.POST['title']
        author = request.POST['author']
        content = request.POST['content']
        image = request.FILES.get('image')
        password = request.POST['password']
        
        new_post = Board.objects.create(
            title = title,
            author = author,
            content = content,
            image = image,
            password = password
        )
        new_post.save()
            
        return HttpResponseRedirect(reverse('qna:main'))




def detail(request, board_id):
    board = get_object_or_404(Board, id=board_id)
    board.hits += 1
    board.save()

    return render(request, 'qna/detail.html', {'board':board})

def delete(request, board_id):
    if request.method == 'POST':

        board = get_object_or_404(Board, id=board_id)
        if board.password == request.POST['password']:
            board.delete()
            return HttpResponseRedirect(reverse('qna:main'))
        else:
            return render(request, 'qna/detail.html', {'board':board, 'error_message': "비밀번호 오류"})
    
    elif request.method == 'GET':
        return HttpResponseRedirect(reverse('qna:datail', args = (board_id,)))
        
    

def search(request):
    if request.method == 'POST':
        searchWord = request.POST['searchStr']
        board_list = Board.objects.filter(Q(title__icontains=searchWord) | Q(content__icontains=searchWord) | Q(author__icontains=searchWord)).distinct().order_by('-create_at')
        totalCnt = board_list.count()
        pagingHelperlns = pagingHelper()
        totalPageList = pagingHelperlns.getTotalPageList(totalCnt, rowsPerPage)

        return render(request, 'qna/main.html', {'boardList': board_list, 'totalCnt': totalCnt, 
                                            'current_page': 1, 'totalPageList': totalPageList})
                                            
    if request.method == 'GET':
        return HttpResponseRedirect(reverse('qna:main'))

capstone/search/views.py
from django.shortcuts import render
from django.http import HttpResponse

def main(request):
    return HttpResponse("검색")

capstone/trend/views.py
from django.shortcuts import render
from django.http import HttpResponse

def main(request):
    return HttpResponse("트렌드")

capstone/users/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from .forms import SignUpForm, LogInForm, UserSearchForm
from django.views.generic.edit import FormView
from .models import User
from django.db.models import Q

def main(request):
    if request.method == 'GET':
        form = LogInForm()
        return render(request, 'users/main.html', {'form': form})

    elif request.method == 'POST':
        form = LogInForm(request.POST)

        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('users:index'))
        else:
            return HttpResponse("등록되지 않은 사용자입니다.")    
    return render(request, 'users/main.html')

def signup(request):
    if request.method == 'GET':
        form = SignUpForm()

        return render(request, 'users/signup.html', {'form':form})
    elif request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('users:index'))
            
        return render(request, 'users/main.html')

def sucess(request):
    return HttpResponse("로그인 성공!")

class SearchFormView(FormView):
    form_class = UserSearchForm
    template_name = 'users/search.html'

    def form_valid(self, form):
        searchWord = form.cleaned_data['search_word']
        user_list = User.objects.filter(Q(name__icontains=searchWord) | Q(email__icontains=searchWord) | Q(bio__icontains=searchWord)).distinct()

        context = {'form': form, 'search_term': searchWord, 'object_list': user_list}
        return render(self.request, self.template_name, context)

capstone/templates/users/main.html
<h1> 최초로그인페이지 </h1>


<form action = "{% url 'users:main' %}" method='post'>
    {% csrf_token %}
    <!-- <input type="input" name = "username" placeholder="please enter Id">
    <input type="password" name = "password" placeholder="please enter PW">
    > -->
    {% for filed in form %}
        <div class = "fieldWrapper">
            {{ filed.errors }}
            {{ filed.label_tag }} {{ filed }}
        </div>
    {% endfor %}
    <input type="submit" value="Log-In">
</form>

<a href="{% url 'users:signup' %}"> 회원가입</a> 　
<a href="">  ID찾기</a> 　
<a href="">  비밀번호찾기</a>

capstone/templates/users/search(원본).html
{% extends "base.html" %}

{% block title %}post_search.html{% endblock %}

{% block content %}
<h1>Blog Search</h1>
<br>

<form action="." method="post"> {% csrf_token %}
    {{ form.as_table }} <!-- form을 테이블 형식으로 표시, 여기서 form은 views에서 넘겨준 PostSearchForm 객체임-->
    <input type="submit" value="Submit" class="btn btn-primary btn-sm">
</form>

<br/><br/>

{% if object_list %}
    {% for post in object_list %}
        <h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
        {{ post.modify_date|date:"N d, Y" }}
        <p>{{ post.description }}</p>
    {% endfor %}
{% elif search_term %}<!-- 검색란이 공란인지 확인-->
    <b><i>Search Word({{ search_term }}) Not Found</i></b>
{% endif %}
{% endblock %}

capstone/templates/users/search.html
<h1>User Search</h1>
<br>

<form action="{% url 'users:search' %}" method="post"> {% csrf_token %}
    {{ form.as_table }} <!-- form을 테이블 형식으로 표시, 여기서 form은 views에서 넘겨준 PostSearchForm 객체임-->
    <input type="submit" value="Submit" class="btn btn-primary btn-sm">
</form>

<br/><br/>

{% if object_list %}
    {% for user in object_list %}
        <h2><a href='{{ User.get_absolute_url }}'>{{ user.name }}</a></h2>  <!-- User모델의 함수 (user:detail)로 넘어가는 링크 -->
        <p>{{ user.email }}</p>
    {% endfor %}
{% elif search_term %}<!-- 검색란이 공란인지 확인-->
    <b><i>Search Word({{ search_term }}) Not Found</i></b>
{% endif %}

capstone/templates/users/signup.html
<h1> 회원가입 페이지 </h1>

<form action="{% url 'users:signup' %}" method="post">
    {% csrf_token %}

    {% for filed in form %}
        <div class = "fieldWrapper">
            {{ filed.errors }}
            {{ filed.label_tag }} {{ filed }}
        </div>
    {% endfor %}
    <input type="submit" value="완료">


</form>

<a href="{% url 'users:main' %}"> Login </a>

capstone/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

capstone/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}